# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [7]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
# # Code to read csv file into Colaboratory:
# !pip install -U -q PyDrive
# from pydrive.auth import GoogleAuth
# from pydrive.drive import GoogleDrive
# from google.colab import auth
# from oauth2client.client import GoogleCredentials
# # Authenticate and create the PyDrive client.
# auth.authenticate_user()
# gauth = GoogleAuth()
# gauth.credentials = GoogleCredentials.get_application_default()
# drive = GoogleDrive(gauth)

In [0]:
# # Import pandas 
# import pandas as pd
# import numpy as np


# link = "https://drive.google.com/open?id=1eYj0HhuFw3hxYk6BoxKOGya0PRMqh5YB"
# fluff, id = link.split('=')
# print (id) 

# downloaded = drive.CreateFile({'id':id}) 
# downloaded.GetContentFile('iris.csv')  
# df = pd.read_csv('iris.csv')
# # Dataset is now stored in a Pandas Dataframe
# df

In [223]:
from sklearn import datasets
import matplotlib.pyplot as plt 
# Load digits dataset
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [224]:
# Create feature matrix
X = iris.data
print(type(X))

# Create target vector
y = iris.target
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [225]:
X
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
# Import `train_test_split` from `sklearn.model_selection`
from sklearn.model_selection import train_test_split

# Split the data up in train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)



## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
#from keras.utils import np_utils
from tensorflow.keras.utils import to_categorical
#Encoding the output class label (One-Hot Encoding)
y_train=to_categorical(y_train,3,dtype='int')
y_test=to_categorical(y_test,3,dtype='int')


In [228]:
y_train

array([[1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0,

In [229]:
y_test

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras.layers import Dense
import keras
#Initialize Sequential Graph (model)
model = tf.keras.Sequential()


## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(Dense(4, activation='relu', input_shape=(4,)))
model.add(Dense(4, activation='relu'))
model.add(Dense(3, activation='softmax'))



## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='categorical_crossentropy',metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [233]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 4)                 20        
_________________________________________________________________
dense_15 (Dense)             (None, 4)                 20        
_________________________________________________________________
dense_16 (Dense)             (None, 3)                 15        
Total params: 55
Trainable params: 55
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [234]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_test,y_test))


Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 3ms/sample - loss: 1.5174 - accuracy: 0.3482 - val_loss: 1.3837 - val_accuracy: 0.2895
Epoch 2/100
112/112 [==============================] - 0s 211us/sample - loss: 1.3323 - accuracy: 0.3482 - val_loss: 1.2646 - val_accuracy: 0.2895
Epoch 3/100
112/112 [==============================] - 0s 222us/sample - loss: 1.2352 - accuracy: 0.3482 - val_loss: 1.2039 - val_accuracy: 0.2895
Epoch 4/100
112/112 [==============================] - 0s 199us/sample - loss: 1.1816 - accuracy: 0.3482 - val_loss: 1.1702 - val_accuracy: 0.2895
Epoch 5/100
112/112 [==============================] - 0s 188us/sample - loss: 1.1510 - accuracy: 0.3482 - val_loss: 1.1418 - val_accuracy: 0.2895
Epoch 6/100
112/112 [==============================] - 0s 199us/sample - loss: 1.1259 - accuracy: 0.3482 - val_loss: 1.1277 - val_accuracy: 0.2895
Epoch 7/100
112/112 [==============================] - 0s 184us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [235]:
model.predict(X_test[0:1])

array([[0.10825843, 0.38305363, 0.50868785]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [236]:
y_test[0:1]

array([[0, 1, 0]])

In [237]:
score = model.evaluate(X_test, y_test,verbose=1)

print(score)


38/38 [==============================] - 0s 148us/sample - loss: 0.7620 - accuracy: 0.7105
[0.7619709843083432, 0.7105263]




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [239]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# Code to read csv file into Colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [1]:
# Import pandas 
import pandas as pd
import numpy as np


link = "https://drive.google.com/open?id=1xoN6aDneJAsEAHAY-sC_ThGvFaUe7_Qf"
fluff, id = link.split('=')
print (id) 

downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('prices.csv')  
df = pd.read_csv('prices.csv')
# Dataset is now stored in a Pandas Dataframe
df

date symbol        open       close         low  \
0       2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998   
1       2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002   
2       2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000   
3       2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000   
4       2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996   
5       2016-01-12 00:00:00   WLTW  115.510002  115.550003  114.500000   
6       2016-01-13 00:00:00   WLTW  116.459999  112.849998  112.589996   
7       2016-01-14 00:00:00   WLTW  113.510002  114.379997  110.050003   
8       2016-01-15 00:00:00   WLTW  113.330002  112.529999  111.919998   
9       2016-01-19 00:00:00   WLTW  113.660004  110.379997  109.870003   
10      2016-01-20 00:00:00   WLTW  109.059998  109.300003  108.320000   
11      2016-01-21 00:00:00   WLTW  109.730003  110.000000  108.320000   
12      2016-01-22 00:00:00   WLTW  111.879997  111.949997  110.190002   
13      2016-01-25 00:00:00   WLTW  111.320000  110.120003  110.000000   
14      2016-01-26 00:00:00   WLTW  110.419998  111.000000  107.300003   
15      2016-01-27 00:00:00   WLTW  110.769997  110.709999  109.019997   
16      2016-01-28 00:00:00   WLTW  110.900002  112.580002  109.900002   
17      2016-01-29 00:00:00   WLTW  113.349998  114.470001  111.669998   
18      2016-02-01 00:00:00   WLTW  114.000000  114.500000  112.900002   
19      2016-02-02 00:00:00   WLTW  113.250000  110.559998  109.750000   
20      2016-02-03 00:00:00   WLTW  113.379997  114.050003  109.639999   
21      2016-02-04 00:00:00   WLTW  114.080002  115.709999  114.080002   
22      2016-02-05 00:00:00   WLTW  115.120003  114.019997  109.709999   
23      2016-02-08 00:00:00   WLTW  113.300003  111.160004  110.459999   
24      2016-02-09 00:00:00   WLTW  111.169998  110.650002  109.639999   
25      2016-02-10 00:00:00   WLTW  106.730003  107.519997  106.360001   
26      2016-02-11 00:00:00   WLTW  105.629997  107.129997  104.110001   
27      2016-02-12 00:00:00   WLTW  108.559998  107.839996  107.070000   
28      2016-02-16 00:00:00   WLTW  109.110001  110.769997  107.010002   
29      2016-02-17 00:00:00   WLTW  110.830002  111.239998  107.970001   
...                     ...    ...         ...         ...         ...   
851234           2016-12-30    WAT  135.240005  134.389999  133.710007   
851235           2016-12-30    WBA   83.459999   82.760002   82.419998   
851236           2016-12-30    WDC   68.550003   67.949997   67.610001   
851237           2016-12-30    WEC   58.980000   58.650002   58.419998   
851238           2016-12-30    WFC   54.889999   55.110001   54.790001   
851239           2016-12-30    WFM   31.059999   30.760000   30.670000   
851240           2016-12-30    WHR  183.800003  181.770004  180.869995   
851241           2016-12-30     WM   71.269997   70.910004   70.750000   
851242           2016-12-30    WMB   30.940001   31.139999   30.889999   
851243           2016-12-30    WMT   69.120003   69.120003   68.830002   
851244           2016-12-30    WRK   51.840000   50.770000   50.529999   
851245           2016-12-30     WU   21.840000   21.719999   21.600000   
851246           2016-12-30     WY   30.450001   30.090000   29.950001   
851247           2016-12-30    WYN   76.849998   76.370003   76.180000   
851248           2016-12-30   WYNN   87.099998   86.510002   85.570000   
851249           2016-12-30    XEC  136.520004  135.899994  135.309998   
851250           2016-12-30    XEL   41.000000   40.700001   40.560001   
851251           2016-12-30     XL   37.360001   37.259998   37.060001   
851252           2016-12-30   XLNX   61.090000   60.369999   60.020000   
851253           2016-12-30    XOM   90.029999   90.260002   90.010002   
851254           2016-12-30   XRAY   58.290001   57.730000   57.540001   
851255           2016-12-30    XRX    8.720000    8.730000    8.700000   
851256           2016-12-30

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [2]:
df_1 = df.drop(['date','symbol'], axis=1)
df_1.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [3]:
print(df_1.shape)
stock_df = df_1[0:1000]
print(stock_df.shape)
stock_df.head()

(851264, 5)
(1000, 5)


open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [16]:
 X = stock_df.iloc[:,0:4]
 Y = stock_df.iloc[:,4:]
 Y = Y['volume'].div(1000000)
 print(type(X))
 print(type(Y))
 print(X) 
 print(Y)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
           open       close         low        high
0    123.430000  125.839996  122.309998  126.250000
1    125.239998  119.980003  119.940002  125.540001
2    116.379997  114.949997  114.930000  119.739998
3    115.480003  116.620003  113.500000  117.440002
4    117.010002  114.970001  114.089996  117.330002
5    115.510002  115.550003  114.500000  116.059998
6    116.459999  112.849998  112.589996  117.070000
7    113.510002  114.379997  110.050003  115.029999
8    113.330002  112.529999  111.919998  114.879997
9    113.660004  110.379997  109.870003  115.870003
10   109.059998  109.300003  108.320000  111.599998
11   109.730003  110.000000  108.320000  110.580002
12   111.879997  111.949997  110.190002  112.949997
13   111.320000  110.120003  110.000000  114.629997
14   110.419998  111.000000  107.300003  111.400002
15   110.769997  110.709999  109.019997  112.570000
16   110.900002  112.580002  109.900002  1

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [14]:
X_arr = X.to_numpy().astype(np.float32)
Y_arr = Y.to_numpy().astype(np.float32)

print(type(X_arr))
print(type(Y_arr))


print("type:",type(X_arr),X_arr)
print("data_type:",Y_arr.dtype, Y_arr)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
type: <class 'numpy.ndarray'> [[123.43 125.84 122.31 126.25]
 [125.24 119.98 119.94 125.54]
 [116.38 114.95 114.93 119.74]
 ...
 [ 28.32  28.77  28.01  28.81]
 [ 44.    44.8   43.75  44.81]
 [ 36.08  37.14  36.01  37.23]]
data_type: float32 [2.163600e+00 2.386400e+00 2.489500e+00 2.006300e+00 1.408600e+00
 1.098000e+00 9.496000e-01 7.853000e-01 1.093700e+00 1.523500e+00
 1.653900e+00 9.443000e-01 7.449000e-01 7.038000e-01 5.631000e-01
 8.961000e-01 6.804000e-01 7.499000e-01 5.742000e-01 6.948000e-01
 8.963000e-01 9.563000e-01 9.971000e-01 1.200500e+00 1.725200e+00
 1.946000e+00 1.319500e+00 9.224000e-01 1.185100e+00 9.215000e-01
 4.409000e-01 1.244300e+00 6.813000e-01 4.112000e-01 4.473000e-01
 5.592000e-01 4.599000e-01 9.716000e-01 6.941000e-01 1.159600e+00
 8.847000e-01 6.920000e-01 8.980000e-01 8.445000e-01 7.965000e-01
 4.168000e-01 5.902000e-01 4.951000e-01 5.158000e-01 5.621000e-01
 8.093000e-01 1.607300e+00 1.001300e+00 7.114000e-0

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [10]:
X = tf.math.l2_normalize(
    X_arr,
    axis=None,
    epsilon=1e-12,
    name=None
)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [11]:
W = tf.zeros(shape=(4, 1)) 
b = tf.zeros(shape=(1))

print(W)
print(b)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function 
def prediction(features, W, b):     
  y_pred = tf.add(tf.matmul(features, W), b)     
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
 @tf.function
 def loss(y_actual, y_predicted):
   diff = y_actual - y_predicted   
   sqr = tf.square(diff)     
   avg = tf.reduce_mean(sqr)     
   return avg 

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(X, y_actual, w, b, learning_rate=0.01):
  # Record mathematical operations on 'tape' to calculate loss     
  with tf.GradientTape() as t:         
    t.watch([w,b])         
    current_prediction = prediction(X, w, b)         
    current_loss = loss(y_actual, current_prediction)          
  # Calculate Gradients for Loss with respect to Weights and Bias     
  dw, db = t.gradient(current_loss,[w, b])          
  # Update Weights and Bias     
  w = w - learning_rate * dw     
  b = b - learning_rate * db          
  return w, b 
  

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [252]:
print(X)
for i in range(100):         
    #W, b = train(X, Y_arr, W, b)   
    W, b = train(X,Y_arr, W, b)  
    print('Current Training Loss on iteration', i, loss(Y_arr, prediction(X, W, b)).numpy())

tf.Tensor(
[[0.02202894 0.02245906 0.02182905 0.02253223]
 [0.02235197 0.02141321 0.02140607 0.02240551]
 [0.0207707  0.02051548 0.02051192 0.02137037]
 ...
 [0.00505436 0.00513467 0.00499903 0.00514181]
 [0.00785282 0.0079956  0.0078082  0.00799738]
 [0.00643931 0.00662849 0.00642682 0.00664455]], shape=(1000, 4), dtype=float32)
Current Training Loss on iteration 0 236.16759
Current Training Loss on iteration 1 235.09299
Current Training Loss on iteration 2 234.06102
Current Training Loss on iteration 3 233.06998
Current Training Loss on iteration 4 232.11781
Current Training Loss on iteration 5 231.20381
Current Training Loss on iteration 6 230.32585
Current Training Loss on iteration 7 229.48265
Current Training Loss on iteration 8 228.67297
Current Training Loss on iteration 9 227.89539
Current Training Loss on iteration 10 227.14832
Current Training Loss on iteration 11 226.43114
Current Training Loss on iteration 12 225.74234
Current Training Loss on iteration 13 225.0808
Current

### Observe values of Weight
- Print the updated values

In [253]:
print(W)

tf.Tensor(
[[0.0547828 ]
 [0.05488191]
 [0.05422735]
 [0.05533117]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [254]:
print(b)

tf.Tensor([4.607657], shape=(1,), dtype=float32)
