# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
# %tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [3]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv("pricesandiris/iris.csv")
#Importing using sklearn library
from sklearn import datasets
iris_ds = datasets.load_iris()
iris_ds

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [5]:
X = iris_ds.data
Y = iris_ds.target
print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=8)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [7]:
from tensorflow.keras.utils import to_categorical
#Encoding the output class label (One-Hot Encoding)
y_train=to_categorical(y_train,3,dtype='int')
y_test=to_categorical(y_test,3,dtype='int')

## Question 5

### Initialize a sequential model
- Define a sequential model

In [8]:
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras.layers import Dense
#Initialize Sequential Graph (model)
model = tf.keras.Sequential()


## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [9]:
#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(Dense(10, activation='relu', input_shape=(4,)))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [10]:
#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='categorical_crossentropy',metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [12]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_test,y_test))

Train on 105 samples, validate on 45 samples
Epoch 1/100
105/105 [==============================] - 1s 9ms/sample - loss: 1.3677 - accuracy: 0.4762 - val_loss: 1.2196 - val_accuracy: 0.3111
Epoch 2/100
105/105 [==============================] - 0s 490us/sample - loss: 1.1658 - accuracy: 0.3429 - val_loss: 1.1172 - val_accuracy: 0.3111
Epoch 3/100
105/105 [==============================] - 0s 475us/sample - loss: 1.0765 - accuracy: 0.3429 - val_loss: 1.0544 - val_accuracy: 0.3111
Epoch 4/100
105/105 [==============================] - 0s 462us/sample - loss: 1.0328 - accuracy: 0.3429 - val_loss: 1.0245 - val_accuracy: 0.3111
Epoch 5/100
105/105 [==============================] - 0s 508us/sample - loss: 0.9982 - accuracy: 0.3429 - val_loss: 0.9955 - val_accuracy: 0.3111
Epoch 6/100
105/105 [==============================] - 0s 693us/sample - loss: 0.9685 - accuracy: 0.3429 - val_loss: 0.9612 - val_accuracy: 0.3111
Epoch 7/100
105/105 [==============================] - 0s 517us/sample - lo

105/105 [==============================] - 0s 437us/sample - loss: 0.4012 - accuracy: 0.9714 - val_loss: 0.4091 - val_accuracy: 0.9778
Epoch 57/100
105/105 [==============================] - 0s 438us/sample - loss: 0.3967 - accuracy: 0.9524 - val_loss: 0.4038 - val_accuracy: 0.9556
Epoch 58/100
105/105 [==============================] - 0s 452us/sample - loss: 0.3866 - accuracy: 0.9333 - val_loss: 0.3934 - val_accuracy: 1.0000
Epoch 59/100
105/105 [==============================] - 0s 454us/sample - loss: 0.3830 - accuracy: 0.9714 - val_loss: 0.3991 - val_accuracy: 0.9111
Epoch 60/100
105/105 [==============================] - 0s 454us/sample - loss: 0.3778 - accuracy: 0.9333 - val_loss: 0.3840 - val_accuracy: 0.9556
Epoch 61/100
105/105 [==============================] - 0s 456us/sample - loss: 0.3700 - accuracy: 0.9429 - val_loss: 0.4013 - val_accuracy: 0.8889
Epoch 62/100
105/105 [==============================] - 0s 448us/sample - loss: 0.3728 - accuracy: 0.9429 - val_loss: 0.3670 

## Question 10

### Make predictions
- Predict labels on one row

In [13]:
model.predict(X_test[0:1])

array([[0.9489073 , 0.0497096 , 0.00138312]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [14]:
y_test[0:1]

array([[1, 0, 0]])

In [15]:
score = model.evaluate(X_test, y_test,verbose=1)

print(score)

45/1 [==================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================



---



# Stock prices dataset
The data is of stock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [16]:
# %tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [17]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [18]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [19]:
# run this cell to upload file if you are using google colab
# from google.colab import files
# files.upload()

df = pd.read_csv('pricesandiris/prices.csv')
df

date symbol        open       close         low  \
0       2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998   
1       2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002   
2       2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000   
3       2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000   
4       2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996   
5       2016-01-12 00:00:00   WLTW  115.510002  115.550003  114.500000   
6       2016-01-13 00:00:00   WLTW  116.459999  112.849998  112.589996   
7       2016-01-14 00:00:00   WLTW  113.510002  114.379997  110.050003   
8       2016-01-15 00:00:00   WLTW  113.330002  112.529999  111.919998   
9       2016-01-19 00:00:00   WLTW  113.660004  110.379997  109.870003   
10      2016-01-20 00:00:00   WLTW  109.059998  109.300003  108.320000   
11      2016-01-21 00:00:00   WLTW  109.730003  110.000000  108.320000   
12      2016-01-22 00:00:00   WLTW  111.879997  111.949997  110.190002   
13      2016-01-25 00:00:00   WLTW  111.320000  110.120003  110.000000   
14      2016-01-26 00:00:00   WLTW  110.419998  111.000000  107.300003   
15      2016-01-27 00:00:00   WLTW  110.769997  110.709999  109.019997   
16      2016-01-28 00:00:00   WLTW  110.900002  112.580002  109.900002   
17      2016-01-29 00:00:00   WLTW  113.349998  114.470001  111.669998   
18      2016-02-01 00:00:00   WLTW  114.000000  114.500000  112.900002   
19      2016-02-02 00:00:00   WLTW  113.250000  110.559998  109.750000   
20      2016-02-03 00:00:00   WLTW  113.379997  114.050003  109.639999   
21      2016-02-04 00:00:00   WLTW  114.080002  115.709999  114.080002   
22      2016-02-05 00:00:00   WLTW  115.120003  114.019997  109.709999   
23      2016-02-08 00:00:00   WLTW  113.300003  111.160004  110.459999   
24      2016-02-09 00:00:00   WLTW  111.169998  110.650002  109.639999   
25      2016-02-10 00:00:00   WLTW  106.730003  107.519997  106.360001   
26      2016-02-11 00:00:00   WLTW  105.629997  107.129997  104.110001   
27      2016-02-12 00:00:00   WLTW  108.559998  107.839996  107.070000   
28      2016-02-16 00:00:00   WLTW  109.110001  110.769997  107.010002   
29      2016-02-17 00:00:00   WLTW  110.830002  111.239998  107.970001   
...                     ...    ...         ...         ...         ...   
851234           2016-12-30    WAT  135.240005  134.389999  133.710007   
851235           2016-12-30    WBA   83.459999   82.760002   82.419998   
851236           2016-12-30    WDC   68.550003   67.949997   67.610001   
851237           2016-12-30    WEC   58.980000   58.650002   58.419998   
851238           2016-12-30    WFC   54.889999   55.110001   54.790001   
851239           2016-12-30    WFM   31.059999   30.760000   30.670000   
851240           2016-12-30    WHR  183.800003  181.770004  180.869995   
851241           2016-12-30     WM   71.269997   70.910004   70.750000   
851242           2016-12-30    WMB   30.940001   31.139999   30.889999   
851243           2016-12-30    WMT   69.120003   69.120003   68.830002   
851244           2016-12-30    WRK   51.840000   50.770000   50.529999   
851245           2016-12-30     WU   21.840000   21.719999   21.600000   
851246           2016-12-30     WY   30.450001   30.090000   29.950001   
851247           2016-12-30    WYN   76.849998   76.370003   76.180000   
851248           2016-12-30   WYNN   87.099998   86.510002   85.570000   
851249           2016-12-30    XEC  136.520004  135.899994  135.309998   
851250           2016-12-30    XEL   41.000000   40.700001   40.560001   
851251           2016-12-30     XL   37.360001   37.259998   37.060001   
851252           2016-12-30   XLNX   61.090000   60.369999   60.020000   
851253           2016-12-30    XOM   90.029999   90.260002   90.010002   
851254           2016-12-30   XRAY   58.290001   57.730000   57.540001   
851255           2016-12-30    XRX    8.720000    8.730000    8.700000   
851256           2016-12-30

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [20]:
df_drop = df.drop(['date','symbol'], axis=1)
df_drop

open       close         low        high      volume
0       123.430000  125.839996  122.309998  126.250000   2163600.0
1       125.239998  119.980003  119.940002  125.540001   2386400.0
2       116.379997  114.949997  114.930000  119.739998   2489500.0
3       115.480003  116.620003  113.500000  117.440002   2006300.0
4       117.010002  114.970001  114.089996  117.330002   1408600.0
5       115.510002  115.550003  114.500000  116.059998   1098000.0
6       116.459999  112.849998  112.589996  117.070000    949600.0
7       113.510002  114.379997  110.050003  115.029999    785300.0
8       113.330002  112.529999  111.919998  114.879997   1093700.0
9       113.660004  110.379997  109.870003  115.870003   1523500.0
10      109.059998  109.300003  108.320000  111.599998   1653900.0
11      109.730003  110.000000  108.320000  110.580002    944300.0
12      111.879997  111.949997  110.190002  112.949997    744900.0
13      111.320000  110.120003  110.000000  114.629997    703800.0
14      110.419998  111.000000  107.300003  111.400002    563100.0
15      110.769997  110.709999  109.019997  112.570000    896100.0
16      110.900002  112.580002  109.900002  112.970001    680400.0
17      113.349998  114.470001  111.669998  114.589996    749900.0
18      114.000000  114.500000  112.900002  114.849998    574200.0
19      113.250000  110.559998  109.750000  113.860001    694800.0
20      113.379997  114.050003  109.639999  114.639999    896300.0
21      114.080002  115.709999  114.080002  116.320000    956300.0
22      115.120003  114.019997  109.709999  116.489998    997100.0
23      113.300003  111.160004  110.459999  113.300003   1200500.0
24      111.169998  110.650002  109.639999  112.110001   1725200.0
25      106.730003  107.519997  106.360001  112.110001   1946000.0
26      105.629997  107.129997  104.110001  109.260002   1319500.0
27      108.559998  107.839996  107.070000  109.430000    922400.0
28      109.110001  110.769997  107.010002  111.300003   1185100.0
29      110.830002  111.239998  107.970001  112.110001    921500.0
...            ...         ...         ...         ...         ...
851234  135.240005  134.389999  133.710007  135.300003    464200.0
851235   83.459999   82.760002   82.419998   83.620003   3343200.0
851236   68.550003   67.949997   67.610001   69.400002   2824100.0
851237   58.980000   58.650002   58.419998   59.119999   1221800.0
851238   54.889999   55.110001   54.790001   55.360001  15095500.0
851239   31.059999   30.760000   30.670000   31.299999   2707500.0
851240  183.800003  181.770004  180.869995  184.289993    458200.0
851241   71.269997   70.910004   70.750000   71.500000   1230600.0
851242   30.940001   31.139999   30.889999   31.650000   3980300.0
851243   69.120003   69.120003   68.830002   69.430000   6872000.0
851244   51.840000   50.770000   50.529999   51.840000    811200.0
851245   21.840000   21.719999   21.600000   21.900000   2538900.0
851246   30.450001   30.090000   29.950001   30.450001   2825300.0
851247   76.849998   76.370003   76.180000   76.970001    524600.0
851248   87.099998   86.510002   85.570000   87.449997   1888500.0
851249  136.520004  135.899994  135.309998  137.559998    466100.0
851250   41.000000   40.700001   40.560001   41.070000   1887600.0
851251   37.360001   37.259998   37.060001   37.419998    959200.0
851252   61.090000   60.369999   60.020000   61.480000   2111700.0
851253   90.029999   90.260002   90.010002   90.699997   9117800.0
851254   58.290001   57.730000   57.540001   58.360001    949200.0
851255    8.720000    8.730000    8.700000    8.800000  11250400.0
851256   49.980000   49.520000   49.360001   50.000000    646200.0
851257   38.720001   38.669998   38.430000   39.000000   6431600.0
851258   63.930000   63.330002   63.160000   63.939999   1887100.0
851259  103.309998  103.199997  102.849998  103.930000    973800.0
851260   43.070000   43.040001   42.689999   43.310001   1938100.0
851261   53.639999   53.529999   53.270000   53.740002   1701

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [21]:
df_1000 = df_drop[0:1000]
df_1000

open       close         low        high      volume
0    123.430000  125.839996  122.309998  126.250000   2163600.0
1    125.239998  119.980003  119.940002  125.540001   2386400.0
2    116.379997  114.949997  114.930000  119.739998   2489500.0
3    115.480003  116.620003  113.500000  117.440002   2006300.0
4    117.010002  114.970001  114.089996  117.330002   1408600.0
5    115.510002  115.550003  114.500000  116.059998   1098000.0
6    116.459999  112.849998  112.589996  117.070000    949600.0
7    113.510002  114.379997  110.050003  115.029999    785300.0
8    113.330002  112.529999  111.919998  114.879997   1093700.0
9    113.660004  110.379997  109.870003  115.870003   1523500.0
10   109.059998  109.300003  108.320000  111.599998   1653900.0
11   109.730003  110.000000  108.320000  110.580002    944300.0
12   111.879997  111.949997  110.190002  112.949997    744900.0
13   111.320000  110.120003  110.000000  114.629997    703800.0
14   110.419998  111.000000  107.300003  111.400002    563100.0
15   110.769997  110.709999  109.019997  112.570000    896100.0
16   110.900002  112.580002  109.900002  112.970001    680400.0
17   113.349998  114.470001  111.669998  114.589996    749900.0
18   114.000000  114.500000  112.900002  114.849998    574200.0
19   113.250000  110.559998  109.750000  113.860001    694800.0
20   113.379997  114.050003  109.639999  114.639999    896300.0
21   114.080002  115.709999  114.080002  116.320000    956300.0
22   115.120003  114.019997  109.709999  116.489998    997100.0
23   113.300003  111.160004  110.459999  113.300003   1200500.0
24   111.169998  110.650002  109.639999  112.110001   1725200.0
25   106.730003  107.519997  106.360001  112.110001   1946000.0
26   105.629997  107.129997  104.110001  109.260002   1319500.0
27   108.559998  107.839996  107.070000  109.430000    922400.0
28   109.110001  110.769997  107.010002  111.300003   1185100.0
29   110.830002  111.239998  107.970001  112.110001    921500.0
..          ...         ...         ...         ...         ...
970   19.240000   18.680000   18.530001   19.430000   9097500.0
971   20.520000   20.290001   19.709999   20.549999   2242100.0
972   12.950000   13.550000   12.720000   13.600000   6205100.0
973   76.059998   75.440002   75.349998   76.370003    864600.0
974   19.620001   19.830000   19.480000   19.830000    709200.0
975   88.000000   87.370003   87.139999   88.239998   1129600.0
976   31.010000   30.959999   30.700001   31.120001   3449300.0
977   35.900002   35.189999   34.930000   35.910000   7517100.0
978   76.620003   77.650002   76.550003   77.790001   2356500.0
979   25.799999   26.420000   25.719999   26.610001   4839200.0
980   30.370001   31.059999   30.309999   31.110001   3684600.0
981   23.120001   22.920000   22.740000   23.129999  14428400.0
982   39.790001   39.610001   39.090000   39.799999   1463300.0
983   24.669997   25.140004   24.669997   25.160000    749600.0
984   11.250000   11.770000   11.200000   11.790000  13355100.0
985    1.630000    1.650000    1.600000    1.660000  11538300.0
986   17.020000   16.860001   16.790001   17.209999   9931300.0
987  257.840004  256.079998  253.050003  257.959995  12906000.0
988   48.099998   48.150002   47.700001   48.369999    369900.0
989   34.529999   34.430000   34.080002   34.750000   2701000.0
990   27.570000   27.790001   27.370000   27.919999   2627800.0
991   14.200000   14.420000   14.120000   14.430000   3258700.0
992   19.900000   19.580000   19.330000   20.059999   5206100.0
993   62.660000   62.299999   62.189999   62.750000   7099000.0
994   29.219999   28.719999   28.629999   29.309999   7795500.0
995   63.310001   63.590000   63.240002   63.639999   2133200.0
996   27.160000   26.990000   26.680000   27.299999   1982400.0
997   28.320000   28.770000   28.010000   28.809999  37152800.0
998   44.000000   44.799999   43.750000   44.810001   6568600.0
999   36.080002   37.139999   36.009998   37.230000   5604300.0

[1000 rows x 5 columns]

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [32]:
X_1000 = df_1000.iloc[:,0:4]
Y_1000 = df_1000.iloc[:,4:]
Y_1000_norm = Y/100000
print(type(X_1000))
print(type(Y_1000_norm))
print(X_1000)
print(Y_1000_norm)

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
           open       close         low        high
0    123.430000  125.839996  122.309998  126.250000
1    125.239998  119.980003  119.940002  125.540001
2    116.379997  114.949997  114.930000  119.739998
3    115.480003  116.620003  113.500000  117.440002
4    117.010002  114.970001  114.089996  117.330002
5    115.510002  115.550003  114.500000  116.059998
6    116.459999  112.849998  112.589996  117.070000
7    113.510002  114.379997  110.050003  115.029999
8    113.330002  112.529999  111.919998  114.879997
9    113.660004  110.379997  109.870003  115.870003
10   109.059998  109.300003  108.320000  111.599998
11   109.730003  110.000000  108.320000  110.580002
12   111.879997  111.949997  110.190002  112.949997
13   111.320000  110.120003  110.000000  114.629997
14   110.419998  111.000000  107.300003  111.400002
15   110.769997  110.709999  109.019997  112.570000
16   110.900002  112.580002  109.900002  112.970001
17

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [33]:
X_np_array = X_1000.to_numpy().astype(np.float32)
# Y_np_array = Y_1000_norm.to_numpy().astype(np.float32)

# X_np_array = X_1000.astype(np.float32)
Y_np_array = Y_1000_norm.astype(np.float32)

print("type:",type(X_np_array),X_np_array)
print("data_type:",Y_np_array.dtype, Y_np_array)

type: <class 'numpy.ndarray'> [[123.43 125.84 122.31 126.25]
 [125.24 119.98 119.94 125.54]
 [116.38 114.95 114.93 119.74]
 ...
 [ 28.32  28.77  28.01  28.81]
 [ 44.    44.8   43.75  44.81]
 [ 36.08  37.14  36.01  37.23]]
data_type: float32 [0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00
 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00
 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00
 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00
 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00 0.e+00
 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05
 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05
 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05
 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05
 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05 1.e-05
 2.e-05 2.e-05 2.e-05 2.e-05 2.e-05 2.e-05 2.e-05

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [34]:
X = tf.math.l2_normalize(
    X_np_array,
    axis=None,
    epsilon=1e-12,
    name=None
)
X

<tf.Tensor: id=3442, shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240552],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [35]:
W = tf.zeros(shape=(4, 1)) 
b = tf.zeros(shape=(1))

print(W)
print(b)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [36]:
@tf.function 
def prediction(features, W, b):     
  y_pred = tf.add(tf.matmul(features, W), b)     
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [37]:
@tf.function
def loss(y_actual, y_predicted):
 diff = y_actual - y_predicted   
 sqr = tf.square(diff)     
 avg = tf.reduce_mean(sqr)     
 return avg 

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [38]:
def train(X, y_actual, w, b, learning_rate=0.01):
  # Record mathematical operations on 'tape' to calculate loss     
  with tf.GradientTape() as t:         
    t.watch([w,b])         
    current_prediction = prediction(X, w, b)         
    current_loss = loss(y_actual, current_prediction)          
  # Calculate Gradients for Loss with respect to Weights and Bias     
  dw, db = t.gradient(current_loss,[w, b])          
  # Update Weights and Bias     
  w = w - learning_rate * dw     
  b = b - learning_rate * db          
  return w, b 

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [39]:
print(X)
for i in range(100):         
    #W, b = train(X, Y_arr, W, b)   
    W, b = train(X,Y_np_array, W, b)  
    print('Current Training Loss on iteration', i, loss(Y_np_array, prediction(X, W, b)).numpy())

tf.Tensor(
[[0.02202894 0.02245906 0.02182905 0.02253223]
 [0.02235197 0.02141321 0.02140607 0.02240552]
 [0.0207707  0.02051548 0.02051192 0.02137037]
 ...
 [0.00505436 0.00513467 0.00499903 0.00514181]
 [0.00785282 0.0079956  0.0078082  0.00799738]
 [0.00643931 0.00662849 0.00642682 0.00664455]], shape=(1000, 4), dtype=float32)
Current Training Loss on iteration 0 1.6270466e-10
Current Training Loss on iteration 1 1.5889905e-10
Current Training Loss on iteration 2 1.5524503e-10
Current Training Loss on iteration 3 1.517352e-10
Current Training Loss on iteration 4 1.4836452e-10
Current Training Loss on iteration 5 1.451275e-10
Current Training Loss on iteration 6 1.4201873e-10
Current Training Loss on iteration 7 1.3903309e-10
Current Training Loss on iteration 8 1.3616565e-10
Current Training Loss on iteration 9 1.3341202e-10
Current Training Loss on iteration 10 1.307674e-10
Current Training Loss on iteration 11 1.2822761e-10
Current Training Loss on iteration 12 1.2578831e-10
Curre

### Observe values of Weight
- Print the updated values

In [40]:
W

<tf.Tensor: id=5609, shape=(4, 1), dtype=float32, numpy=
array([[1.03087160e-07],
       [1.03273656e-07],
       [1.02041902e-07],
       [1.04118989e-07]], dtype=float32)>

### Observe values of Bias
- Print the updated values

In [41]:
b

<tf.Tensor: id=5612, shape=(1,), dtype=float32, numpy=array([8.670426e-06], dtype=float32)>